### PR TITLE
support coredns v1.11.4 and v1.12.0

### PR DESCRIPTION
**Pull request by bzsuni**
[the release 1.11.4](https://github.com/coredns/coredns/releases/tag/v1.11.4)
[the release 1.12.0](https://github.com/coredns/coredns/releases/tag/v1.12.0)

```bash
docker inspect docker.io/coredns/coredns:1.11.4
[
    {
        "Id": "sha256:6316477a0b9ca6ac80c09ecbefcd660b06671f1307152b9a7ffcacb65d9b1d56",
        "RepoTags": [
            "coredns/coredns:1.11.4"
        ],
        "RepoDigests": [
            "coredns/coredns@sha256:4190b960ea90e017631e3e1a38eea28e98e057ab60d57d47b3db6e5cf77436f7"
        ],


docker inspect coredns/coredns:1.12.0
[
    {
        "Id": "sha256:1cf5f116067c67da67f97bff78c4bbc76913f59057c18627b96facaced73ea0b",
        "RepoTags": [
            "coredns/coredns:1.12.0"
        ],
        "RepoDigests": [
            "coredns/coredns@sha256:40384aa1f5ea6bfdc77997d243aec73da05f27aed0c5e9d65bfa98933c519d97"


```

### CODE REVIEW

**Comment by chrisohaver** [comment]
There are some new options in supported plugins that need to be added.  e.g. new `next` option in the `forward` plugin.

**Review by chrisohaver — CHANGES_REQUESTED** [review]
There are some new options in supported plugins that need to be added. e.g. new next option in the forward plugin.

**Comment by chrisohaver** [comment]
@bzsuni, while double checking this I noticed that there are two options missing from cache that should have been added in a prior version.   I opened an issue for it.  Can you fix that in this PR?

**Comment by bzsuni** [comment]
> @bzsuni, while double checking this I noticed that there are two options missing from cache that should have been added in a prior version. I opened an issue for it. Can you fix that in this PR?

I have added the two options, please review

**Comment by bzsuni** [comment]
Could you please review when you have time? Thanks
@chrisohaver

**Comment by bzsuni** [comment]
Do we need a release version？@chrisohaver

**Pull request merged**
