### PR TITLE
Add travis for unit tests

### LINKED ISSUE #7: Add Travis support

### PR DESCRIPTION
**Pull request by rajansandeep**
Fixes #7

### CODE REVIEW

**Comment by rajansandeep** [comment]
@chrisohaver I did a `make test` locally and it generated the `go.sum` and `go.mod` files
Should it be there or should I remove it?

**Comment by rajansandeep** [comment]
Also, I can't seem to kick off travis build :/
Can you enable it? https://travis-ci.org/coredns/corefile-migration

**Comment by rajansandeep** [comment]
Looks like it works!

**Comment by chrisohaver** [comment]
not completely...

**Comment by rajansandeep** [comment]
yeah, oops, need to modify the makefile for codecov.

**Pull request merged**
